### ISSUE TITLE
Historisation auto sur ajout nouvelle commande

### ISSUE THREAD

**Issue by Furaxworld** [jeedom/plugin-z2m#33]
Peux-tu regarder pour supprimer l'historisation (qui se met automatiquement) , lors d'ajout d'une commande?

![image](https://github.com/jeedom/plugin-z2m/assets/96196882/4a5b1a12-ddc3-4f2b-9dc4-8dc1714c1603)

Je n'ai pas trouvé d'où ça vient...
Merci

_Originally posted by @Furaxworld in https://github.com/jeedom/plugin-z2m/issues/31#issuecomment-2006265035_

**Comment by zoic21** [comment]
Bonjour,
C'est normal est voulu, j'ai eu beaucoup de retour d'utilisateur qui ne comprennent pas pourquoi ya pas d'historique car ils ont pas vu la case donc maintenant elle est cochée par defaut.

**Comment by Furaxworld** [comment]
Salut,

Ok si c'est normal et voulu !
