### ISSUE TITLE
[BUG] Erreur fin d'installation dépendances (avec mqtt2)

### ISSUE THREAD

**Issue by Ultraboss77** [jeedom/plugin-z2m#41]
**Décrire le bogue**
Lors de l'installation des dépendances, une erreur est levée à chaque fois lors de la fin du build npm :
```0181|+ npm run build
0182|> zigbee2mqtt@1.39.0 build
0183|> tsc && node index.js writehash
0184|+ chown www-data:www-data -R /var/www/html/plugins/z2m/resources/zigbee2mqtt
0185|+ echo 9
0186|+ php /var/www/html/core/class/../php/jeecli.php plugin dependancy_end z2m
0187|PHP Fatal error:  Uncaught Exception: Le démon MQTT Manager n'est pas démarré in /var/www/html/plugins/z2m/core/class/z2m.class.php:309
0188|Stack trace:
0189|#0 /var/www/html/plugins/z2m/core/class/z2m.class.php(37): z2m::deamon_start()
0190|#1 /var/www/html/core/php/jeecli.php(61): z2m::dependancy_end()
0191|#2 {main}
0192|thrown in /var/www/html/plugins/z2m/core/class/z2m.class.php on line 309
0193|+ echo 10
0194|+ rm /tmp/jeedom_install_in_progress_z2m
0195|+ echo '*******************End of package installation******************'
0196|*******************End of package installation******************
```

Le msg d'erreur n'étant pas renvoyé, j'ai dû corriger une ligne dans la fonction deamon_start()
``throw new Exception(__('Veuillez vérifier la configuration', __FILE__));``
J'ai remplacé le msg d'exception par $deamon_info['launchable_message'] car ma conf étant correcte, le msg était pas cohérent.

En vérifiant les dates d'install des dépendances, je vois que mosquitto est indiqué de quelques secondes de plus que zigbee2mqtt...
Le lancement de l'installation de zigbee2mqtt n'attend pas la fin du 1er, et dans mon cas ça se joue à quelques secondes.

**Reproduire**
Relancer l'installation des dépendances (en ayant mosquitto d'installé via le plugin mqtt2)

**Comportement attendu**
Installation des dépendances et relance mosquitto sans erreur

**Contexte supplémentaire**
Debian 11.10, php 8.3.9, jeedom 4.4.9, z2m beta du 2024-06-04 01:01:48

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour c'est un soucis connu il suffit d'attendre 10min et jeedom corrigera tout et démarrera tout correctement. Je vais voir si je peux améliorer cela mais c'est compliqué car la ou chez vous c'est quelques seconde chez d'autre ca sera quelques minute.
