### ISSUE TITLE
Zigbee-Télécommande IR Intelligente

### ISSUE THREAD

**Issue by domoggvad** [jeedom/plugin-z2m#48]
Bonjour
Pensez-vous possible d'ajouter cee type de telecommande 
https://fr.aliexpress.com/item/1005005828181705.html?srcSns=sns_WhatsApp&spreadType=socialShare&bizType=ProductDetail&social_params=60800586681&aff_fcid=da53ab008ebe4ef8bd2c734f925378b1-1727241570616-01460-_EvV1n49&tt=MG&aff_fsk=_EvV1n49&aff_platform=default&sk=_EvV1n49&aff_trace_key=da53ab008ebe4ef8bd2c734f925378b1-1727241570616-01460-_EvV1n49&shareId=60800586681&businessType=ProductDetail&platform=AE&terminal_id=a69edbfbb07d49119f6b42d970a24da9&afSmartRedirect=y&gatewayAdapt=glo2fra

Merci

**Comment by zoic21** [comment]
Bonjour,
Est elle compatible avec z2m ? Si oui elle est compatible jeedom alors si non il faut leur demander directement.
